// Generated by gencpp from file package_robot/DoCarWashGoal.msg
// DO NOT EDIT!


#ifndef PACKAGE_ROBOT_MESSAGE_DOCARWASHGOAL_H
#define PACKAGE_ROBOT_MESSAGE_DOCARWASHGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_robot
{
template <class ContainerAllocator>
struct DoCarWashGoal_
{
  typedef DoCarWashGoal_<ContainerAllocator> Type;

  DoCarWashGoal_()
    : number_of_cars(0)  {
    }
  DoCarWashGoal_(const ContainerAllocator& _alloc)
    : number_of_cars(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_of_cars_type;
  _number_of_cars_type number_of_cars;





  typedef boost::shared_ptr< ::package_robot::DoCarWashGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_robot::DoCarWashGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoCarWashGoal_

typedef ::package_robot::DoCarWashGoal_<std::allocator<void> > DoCarWashGoal;

typedef boost::shared_ptr< ::package_robot::DoCarWashGoal > DoCarWashGoalPtr;
typedef boost::shared_ptr< ::package_robot::DoCarWashGoal const> DoCarWashGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_robot::DoCarWashGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_robot::DoCarWashGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_robot::DoCarWashGoal_<ContainerAllocator1> & lhs, const ::package_robot::DoCarWashGoal_<ContainerAllocator2> & rhs)
{
  return lhs.number_of_cars == rhs.number_of_cars;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_robot::DoCarWashGoal_<ContainerAllocator1> & lhs, const ::package_robot::DoCarWashGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_robot::DoCarWashGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::DoCarWashGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::DoCarWashGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33bb64012f135ffd1019c71227972263";
  }

  static const char* value(const ::package_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33bb64012f135ffdULL;
  static const uint64_t static_value2 = 0x1019c71227972263ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_robot/DoCarWashGoal";
  }

  static const char* value(const ::package_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 number_of_cars\n"
;
  }

  static const char* value(const ::package_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_of_cars);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoCarWashGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_robot::DoCarWashGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_robot::DoCarWashGoal_<ContainerAllocator>& v)
  {
    s << indent << "number_of_cars: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_cars);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_ROBOT_MESSAGE_DOCARWASHGOAL_H
