// Generated by gencpp from file package_robot/DoCarWashResult.msg
// DO NOT EDIT!


#ifndef PACKAGE_ROBOT_MESSAGE_DOCARWASHRESULT_H
#define PACKAGE_ROBOT_MESSAGE_DOCARWASHRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_robot
{
template <class ContainerAllocator>
struct DoCarWashResult_
{
  typedef DoCarWashResult_<ContainerAllocator> Type;

  DoCarWashResult_()
    : total_cars_cleaned(0)  {
    }
  DoCarWashResult_(const ContainerAllocator& _alloc)
    : total_cars_cleaned(0)  {
  (void)_alloc;
    }



   typedef int32_t _total_cars_cleaned_type;
  _total_cars_cleaned_type total_cars_cleaned;





  typedef boost::shared_ptr< ::package_robot::DoCarWashResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_robot::DoCarWashResult_<ContainerAllocator> const> ConstPtr;

}; // struct DoCarWashResult_

typedef ::package_robot::DoCarWashResult_<std::allocator<void> > DoCarWashResult;

typedef boost::shared_ptr< ::package_robot::DoCarWashResult > DoCarWashResultPtr;
typedef boost::shared_ptr< ::package_robot::DoCarWashResult const> DoCarWashResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_robot::DoCarWashResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_robot::DoCarWashResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_robot::DoCarWashResult_<ContainerAllocator1> & lhs, const ::package_robot::DoCarWashResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_cars_cleaned == rhs.total_cars_cleaned;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_robot::DoCarWashResult_<ContainerAllocator1> & lhs, const ::package_robot::DoCarWashResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_robot::DoCarWashResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_robot::DoCarWashResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::DoCarWashResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::DoCarWashResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::DoCarWashResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::DoCarWashResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_robot::DoCarWashResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2977e980bbc096b3b3c2043d941b53ab";
  }

  static const char* value(const ::package_robot::DoCarWashResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2977e980bbc096b3ULL;
  static const uint64_t static_value2 = 0xb3c2043d941b53abULL;
};

template<class ContainerAllocator>
struct DataType< ::package_robot::DoCarWashResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_robot/DoCarWashResult";
  }

  static const char* value(const ::package_robot::DoCarWashResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_robot::DoCarWashResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"int32 total_cars_cleaned\n"
;
  }

  static const char* value(const ::package_robot::DoCarWashResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_robot::DoCarWashResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_cars_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoCarWashResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_robot::DoCarWashResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_robot::DoCarWashResult_<ContainerAllocator>& v)
  {
    s << indent << "total_cars_cleaned: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_cars_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_ROBOT_MESSAGE_DOCARWASHRESULT_H
