// Generated by gencpp from file package_robot/SumTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef PACKAGE_ROBOT_MESSAGE_SUMTWOINTSRESPONSE_H
#define PACKAGE_ROBOT_MESSAGE_SUMTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_robot
{
template <class ContainerAllocator>
struct SumTwoIntsResponse_
{
  typedef SumTwoIntsResponse_<ContainerAllocator> Type;

  SumTwoIntsResponse_()
    : sum(0)  {
    }
  SumTwoIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumTwoIntsResponse_

typedef ::package_robot::SumTwoIntsResponse_<std::allocator<void> > SumTwoIntsResponse;

typedef boost::shared_ptr< ::package_robot::SumTwoIntsResponse > SumTwoIntsResponsePtr;
typedef boost::shared_ptr< ::package_robot::SumTwoIntsResponse const> SumTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_robot::SumTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_robot::SumTwoIntsResponse_<ContainerAllocator1> & lhs, const ::package_robot::SumTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_robot::SumTwoIntsResponse_<ContainerAllocator1> & lhs, const ::package_robot::SumTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::package_robot::SumTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_robot/SumTwoIntsResponse";
  }

  static const char* value(const ::package_robot::SumTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response\n"
"int64 sum\n"
;
  }

  static const char* value(const ::package_robot::SumTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_robot::SumTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_robot::SumTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_ROBOT_MESSAGE_SUMTWOINTSRESPONSE_H
